### ISSUE TITLE
USER STORY: Select order print-out size

### ISSUE THREAD

**Issue by vikdts** [vikdts/My-First-Agile-Project#5]
As a **warehouse employee,** I can **select the paper size while printing the order details** so that **attach it to different parcel sizes**

# **Acceptance Criteria:**
- Order details include the order id, the shipping address and the list of items in the parcel
- The warehouse employee can select the size of the order details from 3 sizes (A4, A5 and A6)
- Font size used is 12 points
# **Tasks**
- [ ] Design a "print" icon and add it to the order details page
- [ ] Design the print layouts for the different page sizes
- [ ] Create the HTML and CSS for the dropdown menu including the paper sizes
- [ ] Create the code for the model, viewer and controller
- [ ] Test the completed functionality
